services:
  tf2-soundbutton:
    image: tf2-soundbutton:latest
    build: .
    container_name: tf2-soundbutton
    environment:
      PULSE_SERVER: unix:/run/user/${UID}/pulse/native
    volumes:
      # Files cannot be replaced, only modified. Otherwise Docker loses track of them.
      # Make sure "console.log" exists before starting the container,
      # otherwise Docker will create a directory with that name on the host
      - /run/user/${UID}/pulse/native:/run/user/${UID}/pulse/native:ro
      - ${HOME}/.steam/steam/steamapps/common/Team Fortress 2/tf/console.log:/tts/console.log:ro
      - ./chat_soundbutton.sh:/tts/chat_soundbutton.sh:ro
      - ./sounds:/tts/sounds:ro
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - SETUID
      - SETGID
      - CHOWN
      - DAC_OVERRIDE
    tmpfs:
      - /tmp
