services:
  tf2-poll:
    image: tf2-poll:latest
    build: .
    container_name: tf2-poll
    environment:
      PULSE_SERVER: unix:/run/user/${UID}/pulse/native
    volumes:
      # Files cannot be replaced, only modified. Otherwise Docker loses track of them.
      # Make sure "console.log" exists before starting the container,
      # otherwise Docker will create a directory with that name on the host
      - /run/user/${UID}/pulse/native:/run/user/${UID}/pulse/native:ro
      - ${HOME}/.steam/steam/steamapps/common/Team Fortress 2/tf/console.log:/tts/console.log:ro
      - ./chat_poll.sh:/tts/chat_poll.sh:ro
      - ./sounds:/tts/sounds:ro
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
    network_mode: none
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
